name: Publish Python Package to PyPI

on:
  release:
    types: [created]

permissions:
  contents: read

jobs:
  deploy:
    name: Build and publish to PyPI
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: pip
          cache-dependency-path: pyproject.toml

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Build package
        run: |
          python -m build --sdist --wheel .

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
